name: "BundleTool Action"
description: "This action will help you convert your aab to signed apk file."
author: "Mukesh Solanki"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  aabFile:
    description: "Path to your aab file"
    required: true
  keystorePath:
    description: "The path to keystore used to sign the apk"
    required: false
  keystorePassword:
    description: "The keystore password"
    required: false
  keystoreAlias:
    description: "The keystore alias"
    required: false
  keyPassword:
    description: "The password to the key"
    required: false
  bundletoolVersion:
    description: "The version of bundletool to use"
    required: false
    default: "latest"

runs:
  using: "node12"
  main: "dist/index.js"
